/**:
  ros__parameters:
    slave: True
    init_x: -237.764889	
    init_y: -2306.510235
    init_velocity: 0.0
    init_heading: -0.78
    state_frame: 'map'
    odom_child_frame: 'base_link'
    sim_time_step_s: 0.04
    output_time_s: 0.04
    sync_mode: True

    vehicle:
      cog_to_front_axle: 1.228
      cog_to_rear_axle: 1.5618
 
